name: dart_cqrs_example
description: Sample app showing how to write features against dart_cqrs.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.12.0

dependencies:
  dart_cqrs:
    path: ../
  get_it: ^8.3.0
  injectable: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.0
  injectable_generator: ^3.0.0
  lints: ^6.0.0
  test: ^1.25.6
