import 'dart:async';

import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import '../annotations/cqrs_annotations.dart';
import '../model/handler_info.dart';
import '../parser/handler_parser.dart';

/// Generator that creates [HandlerRegistry] registration extensions
/// and, for `@CqrsMicroPackage`, also a concrete [CqrsPackageModule] subclass.
class CqrsGenerator extends Generator {
  const CqrsGenerator({this.parser = const HandlerParser()});

  final HandlerParser parser;

  static const _anyChecker = TypeChecker.any([
    TypeChecker.typeNamed(CqrsInit),
    TypeChecker.typeNamed(CqrsMicroPackage),
  ]);

  @override
  FutureOr<String?> generate(
    LibraryReader library,
    BuildStep buildStep,
  ) async {
    final annotated = library.annotatedWith(_anyChecker);
    if (annotated.isEmpty) return null;

    // Detect whether the annotation is specifically @CqrsMicroPackage by name.
    // CqrsMicroPackage extends CqrsInit, so we check the concrete type name.
    final annotationTypeName =
        annotated.first.annotation.objectValue.type?.element?.name ?? '';
    final bool isMicroPackage = annotationTypeName == 'CqrsMicroPackage';

    final annotation = annotated.first.annotation;
    final moduleName = annotation.peek('moduleName')?.stringValue;
    final customMethodName = annotation.peek('methodName')?.stringValue;
    final customExtensionName = annotation.peek('extensionName')?.stringValue;
    final customModuleClassName = annotation.peek('moduleClassName')?.stringValue;
    final includeDefaults =
        annotation.peek('includeDefaultFactories')?.boolValue ?? true;
    bool useMicroPackage =
        annotation.peek('useMicroPackage')?.boolValue ?? isMicroPackage;

    // Read the list of CqrsPackageModule subclass types provided by the user.
    final moduleTypeNames = <String>[];
    final modulesReader = annotation.peek('modules');
    if (modulesReader?.listValue != null) {
      for (final obj in modulesReader!.listValue) {
        final name = obj.toTypeValue()?.getDisplayString().replaceAll('?', '') ??
            obj.toTypeValue()?.element?.name;
        if (name != null && name != 'dynamic' && name != 'InvalidType') {
          moduleTypeNames.add(name);
        }
      }
    }

    // If constant evaluation did not yield concrete types (e.g. because the
    // module classes are generated by build_runner in the same build step and
    // have not been indexed yet), fallback to AST inspection.
    if (moduleTypeNames.isEmpty || !useMicroPackage) {
      try {
        final session = library.element.session;
        final parsedLib = session.getParsedLibraryByElement(library.element);
        if (parsedLib is ParsedLibraryResult) {
          for (final unit in parsedLib.units) {
            for (final decl in unit.unit.declarations) {
              for (final ann in decl.metadata) {
                final annName = ann.name.name;
                if (annName == 'CqrsInit' || annName == 'CqrsMicroPackage') {
                  final args = ann.arguments?.arguments;
                  if (args != null) {
                    for (final arg in args) {
                      if (arg is NamedArgument) {
                        if (arg.name.lexeme == 'useMicroPackage') {
                          final expr = arg.argumentExpression;
                          if (expr is BooleanLiteral) {
                            useMicroPackage = expr.value;
                          }
                        } else if (arg.name.lexeme == 'modules') {
                          final expr = arg.argumentExpression;
                          if (expr is ListLiteral) {
                            for (final elem in expr.elements) {
                              final src = elem.toSource().trim();
                              if (src.isNotEmpty) {
                                moduleTypeNames.add(src);
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      } catch (_) {
        // Fallback silently if AST extraction is unavailable.
      }
    }
    final bool isCompositor = useMicroPackage && moduleTypeNames.isNotEmpty;
    final bool generateModuleClass = useMicroPackage && moduleTypeNames.isEmpty;

    // Resolve naming for micro-packages or standard modules
    String extensionName;
    if (customExtensionName != null && customExtensionName.isNotEmpty) {
      extensionName = customExtensionName;
    } else if (moduleName != null && moduleName.isNotEmpty) {
      extensionName = 'AutoRegister${_capitalize(moduleName)}Cqrs';
    } else {
      extensionName = 'AutoRegisterCqrs';
    }

    String methodName;
    if (customMethodName != null && customMethodName.isNotEmpty) {
      methodName = customMethodName;
    } else if (moduleName != null && moduleName.isNotEmpty) {
      methodName = 'register${_capitalize(moduleName)}Handlers';
    } else {
      methodName = 'registerGeneratedHandlers';
    }

    // Module class name (only meaningful for micro-package annotations)
    String moduleClassName;
    if (customModuleClassName != null && customModuleClassName.isNotEmpty) {
      moduleClassName = customModuleClassName;
    } else if (moduleName != null && moduleName.isNotEmpty) {
      moduleClassName = '${_capitalize(moduleName)}CqrsModule';
    } else {
      moduleClassName = 'GeneratedCqrsModule';
    }

    // -------------------------------------------------------------------
    // COMPOSITOR MODE: useMicroPackage: true and modules: [...] is non-empty.
    // Handler scanning is DISABLED. Only the compositor CqrsPackageModule
    // class is emitted — no extension, no scan.
    // -------------------------------------------------------------------
    if (isCompositor) {
      final buffer = StringBuffer();
      buffer.writeln('// ignore_for_file: prefer_initializing_formals');
      buffer.writeln();
      _writeCompositorModuleClass(
        buffer,
        moduleClassName: moduleClassName,
        moduleTypeNames: moduleTypeNames,
      );
      return buffer.toString();
    }

    // -------------------------------------------------------------------
    // SCAN MODE: scan exported classes for handlers and emit the
    // HandlerRegistry extension (+ micro-package class if useMicroPackage is true).
    // -------------------------------------------------------------------

    // Collect all class elements accessible from this library and its parts/exports
    final handlers = <HandlerInfo>[];
    final visitedClasses = <String>{};

    void inspectClass(ClassElement classElement) {
      final name = classElement.name;
      if (name != null && !visitedClasses.contains(name)) {
        visitedClasses.add(name);
        final info = parser.parseClass(classElement);
        if (info != null) {
          handlers.add(info);
        }
      }
    }

    // Inspect classes in the current library
    for (final c in library.classes) {
      inspectClass(c);
    }

    // Inspect classes from exported libraries
    final libElement = library.element;
    for (final exported in libElement.exportedLibraries) {
      if (exported.isInSdk) continue;
      for (final c in exported.classes) {
        inspectClass(c);
      }
    }

    final buffer = StringBuffer();

    if (handlers.isEmpty) {
      buffer.writeln('// No CQRS handlers found in scope.');
      buffer.writeln('extension $extensionName on HandlerRegistry {');
      buffer.writeln('  void $methodName() {}');
      buffer.writeln('}');

      if (generateModuleClass) {
        buffer.writeln();
        _writeEmptyModuleClass(buffer, moduleClassName, methodName);
      }

      return buffer.toString();
    }

    // --- Extension on HandlerRegistry ---
    buffer.writeln(
      '/// Generated registration helper for discovered CQRS handlers ($extensionName).',
    );
    buffer.writeln('extension $extensionName on HandlerRegistry {');
    buffer.writeln('  void $methodName({');

    for (final handler in handlers) {
      final paramType = '${handler.className} Function()';
      if (handler.hasDefaultConstructor && includeDefaults) {
        buffer.writeln('    $paramType ${handler.paramName} = ${handler.className}.new,');
      } else {
        buffer.writeln('    required $paramType ${handler.paramName},');
      }
    }

    buffer.writeln('  }) {');

    for (final handler in handlers) {
      switch (handler.kind) {
        case HandlerKind.command:
          buffer.writeln(
            '    registerCommand<${handler.messageTypeName}, ${handler.resultTypeName}>(${handler.paramName});',
          );
        case HandlerKind.query:
          buffer.writeln(
            '    registerQuery<${handler.messageTypeName}, ${handler.resultTypeName}>(${handler.paramName});',
          );
        case HandlerKind.event:
          buffer.writeln(
            '    registerEvent<${handler.messageTypeName}>(${handler.paramName});',
          );
      }
    }

    buffer.writeln('  }');
    buffer.writeln('}');

    // --- Handler-scan CqrsPackageModule (when useMicroPackage is true) ---
    if (generateModuleClass) {
      buffer.writeln(
        '// ignore_for_file: prefer_initializing_formals',
      );
      buffer.writeln();
      _writeModuleClass(
        buffer,
        moduleClassName: moduleClassName,
        methodName: methodName,
        handlers: handlers,
        includeDefaults: includeDefaults,
      );
    }

    return buffer.toString();
  }

  /// Emits a compositor [CqrsPackageModule] that aggregates a fixed list of
  /// sub-modules declared by the user in the annotation's `modules` field.
  ///
  /// Each sub-module is accepted as a required named constructor parameter and
  /// stored in a private field. [register] delegates to
  /// [HandlerRegistry.registerModules].
  void _writeCompositorModuleClass(
    StringBuffer buffer, {
    required String moduleClassName,
    required List<String> moduleTypeNames,
  }) {
    // Derive a camelCase param/field name from each class name:
    // OrdersCqrsModule → ordersCqrsModule
    String paramName(String typeName) =>
        typeName[0].toLowerCase() + typeName.substring(1);

    buffer.writeln(
      '/// Generated compositor [CqrsPackageModule] that aggregates sub-modules.',
    );
    buffer.writeln('///');
    buffer.writeln('/// Usage:');
    buffer.writeln('/// ```dart');
    buffer.writeln('/// registry.registerModule($moduleClassName(');
    for (final t in moduleTypeNames) {
      buffer.writeln('///   ${paramName(t)}: $t(...),');
    }
    buffer.writeln('/// ));');
    buffer.writeln('/// ```');
    buffer.writeln('class $moduleClassName extends CqrsPackageModule {');

    // Constructor
    buffer.writeln('  const $moduleClassName({');
    for (final t in moduleTypeNames) {
      buffer.writeln('    required $t ${paramName(t)},');
    }
    buffer.writeln('  }) :');

    // Initializer list
    final inits = moduleTypeNames
        .map((t) => '_${paramName(t)} = ${paramName(t)}')
        .join(',\n        ');
    buffer.writeln('        $inits,');
    buffer.writeln('        super();');
    buffer.writeln();

    // Private fields
    for (final t in moduleTypeNames) {
      buffer.writeln('  final $t _${paramName(t)};');
    }
    buffer.writeln();

    // register() override
    buffer.writeln('  @override');
    buffer.writeln('  void register(HandlerRegistry registry) {');
    buffer.writeln('    registry.registerModules([');
    for (final t in moduleTypeNames) {
      buffer.writeln('      _${paramName(t)},');
    }
    buffer.writeln('    ]);');
    buffer.writeln('  }');
    buffer.writeln('}');
  }

  /// Emits an empty [CqrsPackageModule] subclass when no handlers are found.
  void _writeEmptyModuleClass(
    StringBuffer buffer,
    String moduleClassName,
    String methodName,
  ) {
    buffer.writeln('/// Generated [CqrsPackageModule] with no registered handlers.');
    buffer.writeln('class $moduleClassName extends CqrsPackageModule {');
    buffer.writeln('  const $moduleClassName() : super();');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  void register(HandlerRegistry registry) {}');
    buffer.writeln('}');
  }

  /// Emits a concrete [CqrsPackageModule] subclass that holds factory functions
  /// as constructor parameters and delegates [register] to the generated extension.
  void _writeModuleClass(
    StringBuffer buffer, {
    required String moduleClassName,
    required String methodName,
    required List<HandlerInfo> handlers,
    required bool includeDefaults,
  }) {
    buffer.writeln(
      '/// Generated [CqrsPackageModule] for auto-discovered CQRS handlers.',
    );
    buffer.writeln('///');
    buffer.writeln('/// Usage:');
    buffer.writeln('/// ```dart');
    buffer.writeln('/// registry.registerModule($moduleClassName(');
    final requiredHandlers =
        handlers.where((h) => !h.hasDefaultConstructor || !includeDefaults);
    for (final h in requiredHandlers) {
      buffer.writeln('///   ${h.paramName}: ${h.className}.new,');
    }
    buffer.writeln('/// ));');
    buffer.writeln('/// ```');
    buffer.writeln('class $moduleClassName extends CqrsPackageModule {');

    // Constructor
    buffer.writeln('  const $moduleClassName({');
    for (final handler in handlers) {
      final paramType = '${handler.className} Function()';
      if (handler.hasDefaultConstructor && includeDefaults) {
        buffer.writeln(
          '    $paramType ${handler.paramName} = ${handler.className}.new,',
        );
      } else {
        buffer.writeln('    required $paramType ${handler.paramName},');
      }
    }
    buffer.writeln('  }) :');

    // Initializer list: bind each param to a private field
    final inits = handlers
        .map((h) => '_${h.paramName} = ${h.paramName}')
        .join(',\n        ');
    buffer.writeln('        $inits,');
    buffer.writeln('        super();');
    buffer.writeln();

    // Private fields
    for (final handler in handlers) {
      buffer.writeln(
        '  final ${handler.className} Function() _${handler.paramName};',
      );
    }
    buffer.writeln();

    // register() override
    buffer.writeln('  @override');
    buffer.writeln('  void register(HandlerRegistry registry) {');
    buffer.writeln('    registry.$methodName(');
    for (final handler in handlers) {
      buffer.writeln('      ${handler.paramName}: _${handler.paramName},');
    }
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('}');
  }

  static String _capitalize(String s) {
    if (s.isEmpty) return s;
    return s[0].toUpperCase() + s.substring(1);
  }
}

