import 'dart:async';

import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import '../annotations/cqrs_annotations.dart';
import '../model/handler_info.dart';
import '../parser/handler_parser.dart';

/// Generator that creates [HandlerRegistry] registration extensions
/// and, for `@CqrsMicroPackage`, also a concrete [CqrsPackageModule] subclass.
class CqrsGenerator extends Generator {
  const CqrsGenerator({this.parser = const HandlerParser()});

  final HandlerParser parser;

  static const _anyChecker = TypeChecker.any([
    TypeChecker.typeNamed(CqrsInit),
    TypeChecker.typeNamed(CqrsMicroPackage),
  ]);

  @override
  FutureOr<String?> generate(
    LibraryReader library,
    BuildStep buildStep,
  ) async {
    final annotated = library.annotatedWith(_anyChecker);
    if (annotated.isEmpty) return null;

    // Detect whether the annotation is specifically @CqrsMicroPackage by name.
    // CqrsMicroPackage extends CqrsInit, so we check the concrete type name.
    final annotationTypeName =
        annotated.first.annotation.objectValue.type?.element?.name ?? '';
    final bool isMicroPackage = annotationTypeName == 'CqrsMicroPackage';

    final annotation = annotated.first.annotation;
    final moduleName = annotation.peek('moduleName')?.stringValue;
    final customMethodName = annotation.peek('methodName')?.stringValue;
    final customExtensionName = annotation.peek('extensionName')?.stringValue;
    final customModuleClassName = annotation.peek('moduleClassName')?.stringValue;
    final includeDefaults =
        annotation.peek('includeDefaultFactories')?.boolValue ?? true;
    bool useMicroPackage =
        annotation.peek('useMicroPackage')?.boolValue ?? isMicroPackage;

    // Read the list of CqrsPackageModule subclass types provided by the user.
    final moduleTypeNames = <String>[];
    final modulesReader = annotation.peek('modules');
    if (modulesReader?.listValue != null) {
      for (final obj in modulesReader!.listValue) {
        final name = obj.toTypeValue()?.getDisplayString().replaceAll('?', '') ??
            obj.toTypeValue()?.element?.name;
        if (name != null && name != 'dynamic' && name != 'InvalidType') {
          moduleTypeNames.add(name);
        }
      }
    }

    // If constant evaluation did not yield concrete types (e.g. because the
    // module classes are generated by build_runner in the same build step and
    // have not been indexed yet), fallback to AST inspection.
    if (moduleTypeNames.isEmpty || !useMicroPackage) {
      try {
        final session = library.element.session;
        final parsedLib = session.getParsedLibraryByElement(library.element);
        if (parsedLib is ParsedLibraryResult) {
          for (final unit in parsedLib.units) {
            for (final decl in unit.unit.declarations) {
              for (final ann in decl.metadata) {
                final annName = ann.name.name;
                if (annName == 'CqrsInit' || annName == 'CqrsMicroPackage') {
                  final args = ann.arguments?.arguments;
                  if (args != null) {
                    for (final arg in args) {
                      if (arg is NamedArgument) {
                        if (arg.name.lexeme == 'useMicroPackage') {
                          final expr = arg.argumentExpression;
                          if (expr is BooleanLiteral) {
                            useMicroPackage = expr.value;
                          }
                        } else if (arg.name.lexeme == 'modules') {
                          final expr = arg.argumentExpression;
                          if (expr is ListLiteral) {
                            for (final elem in expr.elements) {
                              final src = elem.toSource().trim();
                              if (src.isNotEmpty) {
                                moduleTypeNames.add(src);
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      } catch (_) {
        // Fallback silently if AST extraction is unavailable.
      }
    }
    // Resolve naming for micro-packages or standard modules
    String extensionName;
    if (customExtensionName != null && customExtensionName.isNotEmpty) {
      extensionName = customExtensionName;
    } else if (moduleName != null && moduleName.isNotEmpty) {
      extensionName = 'AutoRegister${_capitalize(moduleName)}Cqrs';
    } else {
      extensionName = 'AutoRegisterCqrs';
    }

    String methodName;
    if (customMethodName != null && customMethodName.isNotEmpty) {
      methodName = customMethodName;
    } else if (moduleName != null && moduleName.isNotEmpty) {
      methodName = 'register${_capitalize(moduleName)}Handlers';
    } else {
      methodName = 'registerGeneratedHandlers';
    }

    // Module class name (only meaningful for micro-package annotations)
    String moduleClassName;
    if (customModuleClassName != null && customModuleClassName.isNotEmpty) {
      moduleClassName = customModuleClassName;
    } else if (moduleName != null && moduleName.isNotEmpty) {
      moduleClassName = '${_capitalize(moduleName)}CqrsModule';
    } else {
      moduleClassName = 'GeneratedCqrsModule';
    }

    // Collect all class elements and discover nested micro-package boundaries
    final discoveredModuleClasses = <String>[...moduleTypeNames];
    final handlers = <HandlerInfo>[];
    final visitedClasses = <String>{};
    final visitedLibraries = <LibraryElement>{};

    void inspectClass(ClassElement classElement) {
      final name = classElement.name;
      if (name != null && !visitedClasses.contains(name)) {
        visitedClasses.add(name);
        final info = parser.parseClass(classElement);
        if (info != null) {
          handlers.add(info);
        }
      }
    }

    final bool isRootCompositor = !isMicroPackage && useMicroPackage;

    void visitLibrary(LibraryElement lib, {bool isRoot = false}) {
      if (lib.isInSdk || !visitedLibraries.add(lib)) return;

      if (!isRoot) {
        final nestedModuleClass = _findMicroPackageModuleClass(lib);
        if (nestedModuleClass != null) {
          if (isRootCompositor) {
            // For root init: collect EVERY micro-package module in the entire tree,
            // even nested under nested, so every module is registered manually in root init.
            if (!discoveredModuleClasses.contains(nestedModuleClass)) {
              discoveredModuleClasses.add(nestedModuleClass);
            }
          } else {
            // For a feature micro-package: stop at any nested micro-package boundary
            // so each micro-package module manages only its own direct handlers.
            return;
          }
        }
      }

      // Inspect classes in this library if not root compositor
      if (!isRootCompositor) {
        for (final c in lib.classes) {
          inspectClass(c);
        }
      }

      // Recursively scan exported libraries
      for (final exported in lib.exportedLibraries) {
        visitLibrary(exported, isRoot: false);
      }
    }

    // Start traversal from root library
    visitLibrary(library.element, isRoot: true);

    // If the user explicitly declared `modules: [...]` in the annotation, use that
    // exact list; otherwise fall back to auto-discovered modules.
    final effectiveModuleClasses =
        moduleTypeNames.isNotEmpty ? moduleTypeNames : discoveredModuleClasses;

    final bool shouldEmitModuleClass =
        useMicroPackage && (handlers.isNotEmpty || effectiveModuleClasses.isNotEmpty);

    final buffer = StringBuffer();

    // 1. Emit HandlerRegistry extension if direct handlers exist
    if (handlers.isNotEmpty) {
      buffer.writeln(
        '/// Generated registration helper for discovered CQRS handlers ($extensionName).',
      );
      buffer.writeln('extension $extensionName on HandlerRegistry {');
      buffer.writeln('  void $methodName({');

      for (final handler in handlers) {
        final paramType = '${handler.className} Function()';
        if (handler.hasDefaultConstructor && includeDefaults) {
          buffer.writeln('    $paramType ${handler.paramName} = ${handler.className}.new,');
        } else {
          buffer.writeln('    required $paramType ${handler.paramName},');
        }
      }

      buffer.writeln('  }) {');

      for (final handler in handlers) {
        switch (handler.kind) {
          case HandlerKind.command:
            buffer.writeln(
              '    registerCommand<${handler.messageTypeName}, ${handler.resultTypeName}>(${handler.paramName});',
            );
          case HandlerKind.query:
            buffer.writeln(
              '    registerQuery<${handler.messageTypeName}, ${handler.resultTypeName}>(${handler.paramName});',
            );
          case HandlerKind.event:
            buffer.writeln(
              '    registerEvent<${handler.messageTypeName}>(${handler.paramName});',
            );
        }
      }

      buffer.writeln('  }');
      buffer.writeln('}');
    } else if (!shouldEmitModuleClass) {
      buffer.writeln('// No CQRS handlers found in scope.');
      buffer.writeln('extension $extensionName on HandlerRegistry {');
      buffer.writeln('  void $methodName() {}');
      buffer.writeln('}');
    }

    // 2. Emit CqrsPackageModule subclass if useMicroPackage is true
    if (useMicroPackage) {
      buffer.writeln(
        '// ignore_for_file: prefer_initializing_formals',
      );
      buffer.writeln();
      if (handlers.isEmpty && effectiveModuleClasses.isEmpty) {
        _writeEmptyModuleClass(buffer, moduleClassName, methodName);
      } else {
        _writeUnifiedModuleClass(
          buffer,
          moduleClassName: moduleClassName,
          methodName: methodName,
          handlers: handlers,
          subModuleTypeNames: effectiveModuleClasses,
          includeDefaults: includeDefaults,
        );
      }
    }

    return buffer.toString();
  }

  /// Checks if [lib] contains a `@CqrsMicroPackage` or `@CqrsInit(useMicroPackage: true)`
  /// annotation. If so, returns the module class name (e.g. `'OrdersCqrsModule'`).
  String? _findMicroPackageModuleClass(LibraryElement lib) {
    // 1. Try via source_gen TypeChecker
    try {
      final reader = LibraryReader(lib);
      final annotated = reader.annotatedWith(_anyChecker);
      if (annotated.isNotEmpty) {
        final ann = annotated.first.annotation;
        final typeName = ann.objectValue.type?.element?.name ?? '';
        final bool isMicro = typeName == 'CqrsMicroPackage';
        final bool useMicro = ann.peek('useMicroPackage')?.boolValue ?? isMicro;
        if (useMicro) {
          final customClassName = ann.peek('moduleClassName')?.stringValue;
          if (customClassName != null && customClassName.isNotEmpty) {
            return customClassName;
          }
          final modName = ann.peek('moduleName')?.stringValue;
          if (modName != null && modName.isNotEmpty) {
            return '${_capitalize(modName)}CqrsModule';
          }
          return 'GeneratedCqrsModule';
        }
      }
    } catch (_) {}

    // 2. Fallback via AST inspection
    try {
      final session = lib.session;
      final parsedLib = session.getParsedLibraryByElement(lib);
      if (parsedLib is ParsedLibraryResult) {
        for (final unit in parsedLib.units) {
          for (final decl in unit.unit.declarations) {
            for (final ann in decl.metadata) {
              final annName = ann.name.name;
              if (annName == 'CqrsMicroPackage' || annName == 'CqrsInit') {
                bool isMicro = annName == 'CqrsMicroPackage';
                String? modName;
                String? customClass;
                final args = ann.arguments?.arguments;
                if (args != null) {
                  for (final arg in args) {
                    if (arg is NamedArgument) {
                      if (arg.name.lexeme == 'useMicroPackage') {
                        final expr = arg.argumentExpression;
                        if (expr is BooleanLiteral) {
                          isMicro = expr.value;
                        }
                      } else if (arg.name.lexeme == 'moduleName') {
                        modName = arg.argumentExpression
                            .toSource()
                            .replaceAll("'", '')
                            .replaceAll('"', '');
                      } else if (arg.name.lexeme == 'moduleClassName') {
                        customClass = arg.argumentExpression
                            .toSource()
                            .replaceAll("'", '')
                            .replaceAll('"', '');
                      }
                    }
                  }
                }
                if (isMicro) {
                  if (customClass != null && customClass.isNotEmpty) {
                    return customClass;
                  }
                  if (modName != null && modName.isNotEmpty) {
                    return '${_capitalize(modName)}CqrsModule';
                  }
                  return 'GeneratedCqrsModule';
                }
              }
            }
          }
        }
      }
    } catch (_) {}

    return null;
  }

  /// Emits a unified [CqrsPackageModule] subclass that holds direct handler factories
  /// and/or nested sub-module instances.
  void _writeUnifiedModuleClass(
    StringBuffer buffer, {
    required String moduleClassName,
    required String methodName,
    required List<HandlerInfo> handlers,
    required List<String> subModuleTypeNames,
    required bool includeDefaults,
  }) {
    String paramName(String typeName) =>
        typeName[0].toLowerCase() + typeName.substring(1);

    buffer.writeln(
      '/// Generated [CqrsPackageModule] for auto-discovered CQRS handlers and sub-modules.',
    );
    buffer.writeln('///');
    buffer.writeln('/// Usage:');
    buffer.writeln('/// ```dart');
    buffer.writeln('/// registry.registerModule($moduleClassName(');
    for (final t in subModuleTypeNames) {
      buffer.writeln('///   ${paramName(t)}: $t(...),');
    }
    final requiredHandlers =
        handlers.where((h) => !h.hasDefaultConstructor || !includeDefaults);
    for (final h in requiredHandlers) {
      buffer.writeln('///   ${h.paramName}: ${h.className}.new,');
    }
    buffer.writeln('/// ));');
    buffer.writeln('/// ```');
    buffer.writeln('class $moduleClassName extends CqrsPackageModule {');

    // Constructor
    buffer.writeln('  const $moduleClassName({');
    for (final t in subModuleTypeNames) {
      buffer.writeln('    required $t ${paramName(t)},');
    }
    for (final handler in handlers) {
      final paramType = '${handler.className} Function()';
      if (handler.hasDefaultConstructor && includeDefaults) {
        buffer.writeln(
          '    $paramType ${handler.paramName} = ${handler.className}.new,',
        );
      } else {
        buffer.writeln('    required $paramType ${handler.paramName},');
      }
    }
    buffer.writeln('  }) :');

    // Initializer list
    final inits = <String>[
      for (final t in subModuleTypeNames) '_${paramName(t)} = ${paramName(t)}',
      for (final h in handlers) '_${h.paramName} = ${h.paramName}',
    ];
    buffer.writeln('        ${inits.join(',\n        ')},');
    buffer.writeln('        super();');
    buffer.writeln();

    // Private fields
    for (final t in subModuleTypeNames) {
      buffer.writeln('  final $t _${paramName(t)};');
    }
    for (final handler in handlers) {
      buffer.writeln(
        '  final ${handler.className} Function() _${handler.paramName};',
      );
    }
    buffer.writeln();

    // register() override
    buffer.writeln('  @override');
    buffer.writeln('  void register(HandlerRegistry registry) {');
    if (handlers.isNotEmpty) {
      buffer.writeln('    registry.$methodName(');
      for (final handler in handlers) {
        buffer.writeln('      ${handler.paramName}: _${handler.paramName},');
      }
      buffer.writeln('    );');
    }
    if (subModuleTypeNames.isNotEmpty) {
      buffer.writeln('    registry.registerModules([');
      for (final t in subModuleTypeNames) {
        buffer.writeln('      _${paramName(t)},');
      }
      buffer.writeln('    ]);');
    }
    buffer.writeln('  }');
    buffer.writeln('}');
  }

  /// Emits an empty [CqrsPackageModule] subclass when no handlers are found.
  void _writeEmptyModuleClass(
    StringBuffer buffer,
    String moduleClassName,
    String methodName,
  ) {
    buffer.writeln('/// Generated [CqrsPackageModule] with no registered handlers.');
    buffer.writeln('class $moduleClassName extends CqrsPackageModule {');
    buffer.writeln('  const $moduleClassName() : super();');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  void register(HandlerRegistry registry) {}');
    buffer.writeln('}');
  }

  static String _capitalize(String s) {
    if (s.isEmpty) return s;
    return s[0].toUpperCase() + s.substring(1);
  }
}

