builders:
  cqrs_generator:
    import: "package:cqrs_codegen/builder.dart"
    builder_factories: ["cqrsBuilder"]
    build_extensions: {".dart": [".cqrs.dart"]}
    auto_apply: dependents
    build_to: source
